#
# Project structure
#   <project name>:
#     path: string -> local path to the repository
#     steps: array of strings -> steps in the order you want them to run in
#     behaviours: -> this will only apply to this project, and will override the default ones
#       <behaviour>: -> the name of the behaviour you want to override
#         <key>:  -> the key on the behaviour that you want to override
#

projects:
  project_name:
    skip: false
    path: "some/path/to/your/project"
    steps: ['git:create','changelog', 'ruby-version', 'bundle:update', 'rubocop:fix', 'rspec', 'git:commit', 'gitlab:mr']
    behaviours:
      changelog:
        title: "Update ruby dependencies and ruby version"
      ruby_version:
        version: 3.3.6

behaviours: # this will apply to all of the projects
  changelog:
    title: "Upgrade ruby dependencies"
  git:
    branch_prefix: "upgrade_ruby_dependencies"
    message: "Upgrade ruby dependencies"
  bundle:
    skip_changes: false # recommended false

misc:
  skip_version_check: false

languages:
  ruby:
    manager: "rbenv"