projects:
  autointerface:
    path: '/Users/andrei.maga/Desktop/Dev/apps/autointerface'
    steps: ['git:create','changelog','bundle:update', 'rspec']
    behaviours:
      changelog:
        title: 'Update ruby'

behaviours:
  changelog:
    title: 'Upgrade ruby dependencies'
  git:
    branch_prefix: 'upgrade_ruby_dependencies'
    message: 'Upgrade ruby dependencies'
  bundle:
    skip_changes: true