#
# Project structure
#   <project name>:
#     path: string -> local path to the repository
#     steps: array of strings -> steps in the order you want them to run in
#     behaviours: -> this will only apply to this project, and will override the default ones
#       <behaviour>: -> the name of the behaviour you want to override
#         <key>:  -> the key on the behaviour that you want to override
#

projects:
  project_name:
    skip: false
    path: "some/path/to/your/project"